# Generated by Django 5.1.3 on 2024-12-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BinanceSpotKline1m",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_time", models.DateTimeField()),
                ("symbol", models.CharField(max_length=255)),
                ("open_time", models.CharField(max_length=255)),
                ("open_time_date", models.DateTimeField()),
                ("open", models.DecimalField(decimal_places=8, max_digits=50)),
                ("high", models.DecimalField(decimal_places=8, max_digits=50)),
                ("low", models.DecimalField(decimal_places=8, max_digits=50)),
                ("close", models.DecimalField(decimal_places=8, max_digits=50)),
                ("volume", models.DecimalField(decimal_places=8, max_digits=50)),
                ("close_time", models.CharField(max_length=255)),
                ("close_time_date", models.DateTimeField()),
                ("amount", models.DecimalField(decimal_places=8, max_digits=50)),
                (
                    "number_of_trades",
                    models.DecimalField(decimal_places=8, max_digits=50),
                ),
                ("buy_volume", models.DecimalField(decimal_places=8, max_digits=50)),
                ("buy_amount", models.DecimalField(decimal_places=8, max_digits=50)),
            ],
        ),
        migrations.CreateModel(
            name="BinanceSpotKlineDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_time", models.DateTimeField()),
                ("symbol", models.CharField(max_length=255)),
                ("open_time", models.CharField(max_length=255)),
                ("open_time_date", models.DateTimeField()),
                ("open", models.DecimalField(decimal_places=8, max_digits=50)),
                ("high", models.DecimalField(decimal_places=8, max_digits=50)),
                ("low", models.DecimalField(decimal_places=8, max_digits=50)),
                ("close", models.DecimalField(decimal_places=8, max_digits=50)),
                ("volume", models.DecimalField(decimal_places=8, max_digits=50)),
                ("close_time", models.CharField(max_length=255)),
                ("close_time_date", models.DateTimeField()),
                ("amount", models.DecimalField(decimal_places=8, max_digits=50)),
                (
                    "number_of_trades",
                    models.DecimalField(decimal_places=8, max_digits=50),
                ),
                ("buy_volume", models.DecimalField(decimal_places=8, max_digits=50)),
                ("buy_amount", models.DecimalField(decimal_places=8, max_digits=50)),
            ],
        ),
    ]
